---
- name: build new machine
  hosts: host2
  become: yes
  gather_facts: no
  roles: 
  - role: libvirt-guest

- name: check new machine
  hosts: hypervisor
  become: no
  gather_facts: no
  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30

