#
- name: build the service
  hosts: provisioner
  become: yes
  gather_facts: no
  tasks: 
  - name: I got nothing
    debug: 
      msg: err.....

# similar to Satellite?
#
# server certificate missing from this.
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html/installing_capsule_server/installing-capsule-server#configuring-capsule-server-with-ssl-certificates
# katello-certs-check \
#   -t capsule  \
#   -c /etc/pki/tls/certs/capsule1.lab.example.com.pem \
#   -k /etc/pki/tls/private/capsule1.lab.example.com.key  \
#   -b /etc/pki/ca-trust/source/anchors/ca-certificate.pem
#
# something like 
#
# DNS
#
# firewall
# firewall-cmd --info-service=RH-Satellite-6
# firewall-cmd --permanent --add-service=RH-Satellite-6
# firewall-cmd --permanent --add-service=https
# firewall-cmd --reload
#
# capsule register and update
# subscription-manager register someguy somepass
# dnf update
# systemctl reboot
#
# satellite
# create content view with repos
#  rhel-8-for-x86_64-appstream-rpms                  Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
#  rhel-8-for-x86_64-baseos-rpms                     Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
#  satellite-capsule-6.11-for-rhel-8-x86_64-rpms     Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 (RPMs)
#  satellite-maintenance-6.11-for-rhel-8-x86_64-rpms Red Hat Satellite Maintenance 6.11 for RHEL 8 x86_64 (RPMs)
# not convinced this one is needed
#  satellite-utils-6.11-for-rhel-8-x86_64-rpms    
# 
# create activation key with content view
#
# create /root/.ssh/id_rsa.pub 
# copy /root/.ssh/id_rsa.pub to capsule1:/root/.ssh/authorized_keys 
#
# capsule
# ??? subscription-manager unregister
# subscription-manager register --activationkey rhel8actkey --org 'myorg'
#  install RPM packages
# dnf module enable satellite-capsule:el8
# dnf install satellite-capsule
#
# satellite
#   mkdir /root/capsule_cert
#   CAPSULE=capsule1.lab.example.com
#   scp $CAPSULE:/etc/pki/tls/certs/$CAPSULE.pem /etc/pki/tls/certs/$CAPSULE.pem
#   scp $CAPSULE:/etc/pki/tls/private/$CAPSULE.key /etc/pki/tls/private/$CAPSULE.key
# run certificate generation command
# see --certs-update-server for renewal
# adds many files in /root/ssl-build/capsule1.lab.example.com/
#   capsule-certs-generate \
#     --foreman-proxy-fqdn "$CAPSULE" \
#     --certs-tar  "~/$CAPSULE-certs.tar" \
#     --server-cert "/etc/pki/tls/certs/$CAPSULE.pem" \
#     --server-key "/etc/pki/tls/private/$CAPSULE.key" \
#     --server-ca-cert "/etc/pki/ca-trust/source/anchors/ca-certificate.pem" 

# copy satellite-installer command
# scp ~/$CAPSULE-certs.tar root@capsule1.lab.example.com:~/$CAPSULE-certs.tar
#
# capsule
# run satellite-installer command
#   satellite-installer \
#     --scenario capsule \
#     --certs-tar-file                              "/root/capsule1.lab.example.com-certs.tar"\
#     --foreman-proxy-register-in-foreman           "true"\
#     --foreman-proxy-foreman-base-url              "https://satellite1.lab.example.com"\
#     --foreman-proxy-trusted-hosts                 "satellite1.lab.example.com"\
#     --foreman-proxy-trusted-hosts                 "capsule1.lab.example.com"\
#     --foreman-proxy-oauth-consumer-key            "T5GYnDeyWMzwX4hkj9B7SCYrL63BxXCc"\
#     --foreman-proxy-oauth-consumer-secret         "myDfuvGSLqbRhXrwUbMc6ESa4fZhfjDj"

#
# satellite
# fix org and location
# sync content
# hammer capsule content synchronize  --name capsule1.lab.example.com
#
# capsule
# checks
# satellite-maintain service list
# satellite-maintain health check

