
- name: build the virtual hardware, install OS, and install apps
  ansible.builtin.import_playbook: create-machine.yml

- name: install supporting apps
  ansible.builtin.import_playbook: install-apps.yml

- name: install service
  ansible.builtin.import_playbook: build-service.yml

